server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_eshop
    username: postgres
    password: admin
#  flyway:
#    baseline-on-migrate: true